project:
  type: website

website:
  title: "ODSC-ggplot2-west"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: slides/slides.qmd
        text: Slides

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

