project:
  type: website
  output-dir: docs

website:
  title: "ODSC-ggplot2-west"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
    right:
      - href: slides/slides.qmd
        text: Slides
      - icon: github
        href: https://github.com/mjfrigaard/odsc-west-ggplot2-2022
      - icon: twitter
        href: https://twitter.com/mjfrigaard

format:
  html:
    theme:
      dark: [cyborg, styles.scss]
      light: [minty, styles-dark.scss]
    css: styles.css
    toc: true

editor: source

