project:
  type: website
  output-dir: docs

website:
  title: "ODSC-ggplot2-west"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: slides/slides.qmd
        text: Slides

format:
  html:
    theme:
      light: [minty, styles-dark.scss]
      dark: [cyborg, styles.scss]
    css: styles.css
    toc: true

editor: source

